alphagov/notifications-node-client

README.md
authentication.js
package.json
spec/authentication.js

We’ve eased up the restrictions on our JWT tokens so that they no longer have to be signed with the request method and path, and the body of the request (for `POST` requests).
This happened here:
alphagov/notifications-api#226
This commit makes similar changes to those we did for the Python client: alphagov/notifications-python-client@277663e
Because this isn’t Python.
Major change because:
- `create_govuk_notify_token` renamed to `createGovukNotifyToken`
- the number of arguments it takes have been reduced

Remove req and payload from JWT tokens

---

.gitignore
client/api_client.js
client/authentication.js
client/notification.js
index.js
package.json
spec/api_client.js
spec/authentication.js
spec/notification.js

To make the library more useful for integrators, this adds client/notification.js which defines the standard notify api (with reference to  Notify's other client libraries).
Exposed api currently consists of 3 methods: sendEmail, sendSms, getNotificationById.This can be fleshed out further in future. Basic tests included. These could also be expanded.

Add explicit notify api and expose

---

client/notification.js
package.json

The wrapper was always passing three arguments to the constructor. eg `new NotifyClient('abc123')` would result in `ApiClient` getting called with (`abc123`, `undefined`, `undefined`).
Because we count the arguments in `ApiClient` to determine what they mean this completely broke the client, because it was trying to use the API key as the base url, `undefined` as the API key and `undefined` as the service ID.
Luckily we hadn’t published the client, so this didn’t impact any actual users.
This commit does some Javascript gymnastics to always call the constructor with the same number of arguments that the wrapper is given.
Technique taken from: http://stackoverflow.com/a/8843181/147318
> A bit of explanation: We need to run new on a function that takes a limited number of arguments. The …

Fix broken client initialisation

---

README.md

Make it match the SMS example.

Add missing arguments to sendEmail documentation

---

CHANGELOG.md
README.md
client/notification.js
package.json
spec/integration/schemas/v2/GET_template_by_id.json
spec/integration/schemas/v2/GET_templates_response.json
spec/integration/schemas/v2/POST_template_preview.json
spec/integration/schemas/v2/definitions.json
spec/integration/test.js
spec/notification.js

This adds new methods for template retrieval and preview. Additionally the `README` has been updated to demonstrate how to catch errors.
The following template methods (with tests) have been added:
1) `getTemplateById` - retrieve a single template
2) `getTemplateByIdAndVersion` - retrieve a specific version for a desired template
3) `getAllTemplates` - retrieve all templates (can filter by type)
4) `previewTemplateById` - preview a template with personalisation applied
There was also some general refactoring, particularly in the unit tests.

Add new template get/post methods 

---

README.md

If you copy and paste the example code then our examples of what to do with responses is very unhelpful, especially if you don’t know a lot of JS. Specifically it means any error messages returned from the API get squashed and never show up in the console, so it’s hard to understand what, if anything, has gone wrong.

Add logging of responses to example code

---

README.md

It causes a syntax error when you copy-paste this code into your app.

Fix errant semicolon in documentation

---

README.md

For people who don’t know much Node, this missing flag is just another thing that can trip them up.
For people who do have a lot of Node experience, they can choose to remove the `--save` flag if (for whatever reason) they don’t really want it.

Add to `package.json` by default

---

package.json

Remove Restler

---

package.json

Adds option to pass in a proxy for the client to use.
See https://github.com/alphagov/notifications-node-client/pull/28

Minor version bump to 3.2.0

---

CHANGELOG.md
README.md
client/notification.js
package.json
script/generate_docker_env.sh
spec/integration/schemas/v2/POST_notification_email_response.json
spec/integration/test.js
spec/notification.js

In order to support multiple email reply to's, the node client needs to be updated to provide the argument for the Notify API
- added support for email_reply_to_id
- refactored README.md in line with [python client docs](https://github.com/alphagov/notifications-python-client/blob/master/README.md)
Reference - https://www.pivotaltracker.com/story/show/150440099

Add optional email_reply_to_id

---

README.md

Update README as `null` will not work in the node client for optional arguments that are not used so use `undefined`

Updated README to use `undefined`

---

CHANGELOG.md
README.md
client/notification.js
package.json
script/generate_docker_env.sh
spec/integration/test.js
spec/notification.js

When using the `sendSms` function, you can now choose to specify which
sender you want the notification to come from by passing in an
`smsSenderId`. If this is not included, the SMS notification will come
from the default sender.
[Pivotal story](https://www.pivotaltracker.com/story/show/152106587)

Allow sendSms to accept an smsSenderId

---

spec/api_client.js
spec/notification.js

The date was not being mocked in the `api_client.js` and `notification.js`
unit tests, which was causing these to randomly fail. This is because
the date gets used to generate a Notify token for the request header. By
using the real date, the request that we mocked using Nock and the request
that we attempted to make would occasionally have different headers.

Fix randomly failing unit tests by mocking date

---

CHANGELOG.md
README.md
client/notification.js
package.json
spec/integration/test.js
spec/notification.js

Changed `sendSms`, `sendEmail` and `sendLetter` functions to accept an `options` object as a parameter. These functions were taking an increasing number of optional arguments. Passing in an options object simplifies them and means that we don't need to pass in `undefined` when we don't want to use all the arguments.
This is a breaking change to these functions, so requires a major version bump.

Change arguments for sendSms, sendEmail and sendLetter

---

CHANGELOG.md
client/authentication.js
package.json

The Crypto dependency is deprecated, but is also is not being used, so can be removed.
This addresses issue #37.

Remove unused Crypto dependency

---

spec/integration/test.js

previously templates table has \n but no \r, we now read from templates_history which has \r\n, so should update test. templates table should also really have \r as well.

Make integration tests expect \r in template content

---

README.md
client/notification.js
package.json
spec/notification.js

With the breaking change in version 4.0.0, we reduced the amount of parameters by asking that they are supplied in an options dict.
However, this can silently do unexpected things if the person was previously passing in a personalisation dict, and forgets to update their call. We can't catch 100% of those errors, but we can catch obvious things, like the options dict containing things we don't expect.
Also, lots of linter errors and test refactoring. Viewing commit by commit with whitespace off highly recommended!

Reject bad options

---

package.json
spec/integration/test.js

We have been having audit warnings from npm audit when using
notifications-node-client in paas-admin. This PR fixes this issue.

Update dependencies to solve audit warnings

---

CHANGELOG.md
DOCUMENTATION.md
README.md
package.json
spec/integration/schemas/v2/GET_notification_response.json

The `.getNotificationById()` and `.getNotifications()` functions now return `created_by_name` in their responses, so this has been documented and the schema for the integration tests updated.
The version has been bumped from 4.1.0 to 4.2.0 as a result. (Although the `package.json` was previously updated to 4.1.1 in #47, it appears that 4.1.1 was never released - the latest version on NPM is still 4.1.0)

Add 'created_by_name' to the responses when getting notifications

---

CHANGELOG.md
DOCUMENTATION.md
README.md
package.json
spec/integration/schemas/v2/GET_template_by_id.json
spec/integration/test.js

The name of the template is now returned by these two functions:
* `getTemplateById()`
* `getTemplateByIdAndVersion()`
No changes to the code are necessary to make this work, but this PR updates the documentation, adds integration tests and bumps the version.
[Pivotal story](https://www.pivotaltracker.com/story/show/160020331)

Return 'name' when fetching a template

---

CHANGELOG.md
DOCUMENTATION.md
client/notification.js
package.json
spec/integration/schemas/v2/GET_notification_response.json
spec/integration/schemas/v2/POST_notification_letter_response.json
spec/integration/test.js
spec/notification.js

Users will be able to postage when sending precompiled letters

Enable setting postage when sending precompiled letters

---

Dockerfile

Recently, we have changed the Dockerfile in this repo, so it conforms
with our new Concourse pipeline. Yet, this made it incompatible with
Jenkins, and it turned out we are still running integration tests
on Jenkins when deploying the API.
So now we will have two Dockerfiles to help both Concourse and
Jenkins jobs run smoothly in the transition period.

Fix node client integration tests on Jenkins

---

CHANGELOG.md
DOCUMENTATION.md
client/api_client.js
client/notification.js
package.json
spec/integration/schemas/v2/POST_notification_precompiled_letter_response.json
spec/integration/test.js
spec/notification.js

Let our users get a pdf for a letter that they have sent.
It's the same feature like this PR, just in Node: https://github.com/alphagov/notifications-python-client/pull/144/files
Also fix an error in functional test for sending a precompiled letter.

Get letter pdf

---

DOCUMENTATION.md

When mentioning the optional argument `email_reply_to_id` It should say across all clients:
> You can leave out this argument if your service only has one reply-to email address, or you want to use the default email address.
Similarly, for `smsSenderId`, all clients should use:
> You can leave out this argument if your service only has one text message sender, or if you want to use the default sender.
Pivotal story: https://www.pivotaltracker.com/story/show/170575582

Consistent context for email_reply_to_id and smsSenderId across our client documentation (Node)

---

Dockerfile

We think we may have some sub-dependencies which aren’t working with this older version of Node. Let’s try bringing it up to date to see if that resolves things.

Update Node to latest long-term-supported version

---

CHANGELOG.md
client/api_client.js
package.json
spec/api_client.js

This is a rebased version of https://github.com/alphagov/notifications-node-client/pull/113 which includes a version bump and changelog entry. Set up in a new branch so it can run against our CI system as the original PR was from an external contributor.
`__dirname` is a global value made available to Node at runtime. This
will provide the directory where the exucuting file is located. As the
client files are static and always run from the same context, relying on
`__dirname` should not be required here.
Removing this path concatination would also resolve a corner case if the
library is being built by a code bundler that replaces the global value
of `__dirname` (this is an edge case and not default behaviour however may be
set by some configurations).
If the files are being bundled, …

BAU: remove __dirname global call from api client

---

CONTRIBUTING.md
DOCUMENTATION.md
spec/integration/test.js

We’re renaming the ‘Team and whitelist’ key in https://github.com/alphagov/notifications-admin/pull/3479
This commit updates the documentation to match.

Rename whitelist to guest list

---

CHANGELOG.md
DOCUMENTATION.md
client/notification.js
package.json
spec/integration/test.js
spec/notification.js

This will allow node client to ensure CSV files they upload are
downloaded as .csv files rather than .txt files.
This should be analagous to alphagov/notifications-python-client#165

Add isCsv argument to prepareUpload function

---

CHANGELOG.md
DOCUMENTATION.md
package.json
spec/integration/schemas/v2/GET_template_by_id.json
spec/integration/test.js

When notifications-api returns a template it now includes the `letter_contact_block` in the data. This field is automatically returned for the `getTemplateById`, `getTemplateByIdAndVersion` and `getAllTemplates` functions. This change adds the documentation and tests for it and bumps the version of the client.

Add letter_contact_block to the template responses

---

DOCUMENTATION.md

The client documentation talks about address lines 1-6 and postcode (including mandatory nature of address lines 1,2 and postcode). Now that we are supporting address lines 1-7 we need to update the documentation to reflect this.
There is a question about what we should say in the docs about the mapping that we do from postcode, or that it is sort of degraded, but needs a bit of a thought for that.
After we have done this story, services will see the new address personalisation that we require and understand that it won’t be a breaking change for them.

Update address fields to include line 7

---

CHANGELOG.md
DOCUMENTATION.md
client/api_client.js
client/notification.js
package.json
spec/api_client.js
spec/integration/test.js
spec/notification.js

Requests has been deprecated and so we replace it with a more modern
library. This will mean some small breaking changes for users which are
noted by the version bump and changelog records.
Also fixes the `User-agent` header to be `User-Agent` as per the
docs:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent
- Please review line by line for a general code review
- Have a think if there is anything missing from the changelog or ways we could improve the experience for developers upgrading
- Acknowledge the decision that the published docs will be out of date with older versions of the client (but that appears to be a pattern we already use)
- General thumbs up that assuming the code is all 'correct', this we still want to make this change as it will mean a major …

Move from `request-promise` to `axios`

---

client/api_client.js
package.json

Adds a missing semicolon, spotted in https://github.com/alphagov/notifications-node-client/issues/137 (thanks @neilbmclaughlin).
See the message from the first commit for more details on the issue and fix.

Add missing comma

---

.gitignore
CHANGELOG.md
Makefile
package-lock.json
package.json

As requested in https://github.com/alphagov/notifications-node-client/issues/150
Note, our other approach could be to set a range so someone can install any version between 0.21.1 and 0.25.x but I'm not sure if this is better or not than just asking everyone to upgrade to a higher version of axios to use our client.
Note, in an ideal world we could pin to 0.x.x but axios seem to release breaking changes in their minor version bumps meaning that any minor release they do could technically break our client (although it is unlikely)

Bump axios version to ^0.25.0

---

CHANGELOG.md
client/api_client.js
client/notification.js
package-lock.json
package.json

We were using Underscore's `_.extend(...` method for shorthand deep inheritance.
For our purposes, we can use `Object.assign(...` instead and remove a package dependency.
See https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_extend
Removes a reasonably large third party utility package dependency, of which we were only using a single method.

Remove underscore JS package dependency

---

CHANGELOG.md
DOCUMENTATION.md
client/notification.js
package.json
spec/notification.js

Adds client support for the new 'confirm email before download' and 'custom retention period' features when sending a file by email.
Bumps the client to v5.2.0

Add support for new send a file features

---

CHANGELOG.md
package-lock.json
package.json

Addresses a high-level vulnerability here:
https://cve.report/CVE-2022-23529
The migration notes for bumping this package suggest this will drop support for node versions <12 (https://github.com/auth0/node-jsonwebtoken/wiki/Migration-Notes:-v8-to-v9). Need to check+confirm what versions we currently support.
Resolves #167

Bump jsonwebtoken

---

CHANGELOG.md
Dockerfile
package-lock.json
package.json

Attempt 2 at https://github.com/alphagov/notifications-node-client/pull/163
Includes a bump of the docker node version to v18, which is the current LTS. Previously it was on node v12, which is well out of maintenance/support now.
We also bump the minimum supported engine for the node client to v14, which is the minimum currently-maintained node version. This is 1) a reasonable thing to do generally, but also 2) required for the mocha bump.
This PR also bumps indirect dependency `minimatch`, which is currently reported by Dependabot for this vulnerability: https://github.com/alphagov/notifications-node-client/security/dependabot/9
Bump node client to v7.0.0
- …

Bump mocha version

---

CHANGELOG.md
client/notification.js
package.json
spec/notification.js

There is a bug that coalesces false to null, which ends up applying the default action of enabling email confirmation (by the API)

Fix disabling confirm email step

---

CHANGELOG.md
package-lock.json
package.json

This pulls in the latest version of Axios which has some security vulnerabilities fixed.
I asked on GDS Slack whether we should be specifying the oldest compatible version of the dependency or the latest version.
This is the response I got:
> I would specify the latest version that has the vulnerability patched.
>
> If you think that might result in a breaking change for your consumers, I'd then make a new major version of your package,
> describing the potential for breaking changes.
>
> Version numbers are cheap, so you should feel free to make as many of them as possible.
***
Fixes #187

Bump Axios to version 1.6.1

---

CHANGELOG.md
client/notification.js
package-lock.json
package.json
spec/notification.js

Update client for the new document download feature which allows specifying a download filename for files sent by email.
This supercedes the old `isCsv` parameter that was inconsistent at best.
Given this, we are dropping support for `isCsv` altogether which lets us clean up the interface for the `prepareUpload` function to now only use the new options dict.

Allow setting custom filenames for documents

---

package-lock.json
package.json
spec/integration/schemas/v2/GET_notification_response.json

New fields have been added to the response of `get_notification(notificationId)` endpoint
- cost_in_pounds
- is_cost_data_ready
- cost_details:
-- **Nested fields for letters**:
--- billable_sheets_of_paper
--- postage
-- **Nested fields for sms**:
--- billable_sms_fragments
--- international_rate_multiplier
--- sms_rate
Based on the addition of these new fields, this PR updates the node client to align with the changes.
[3. Add GET notification cost data to API clients and API client docs](https://trello.com/c/5VZrBNpU/845-3-add-get-notification-cost-data-to-api-clients-and-api-client-docs)
- [notifications-tech-docs repository](https://github.com/alphagov/notifications-tech-docs/blob/main/source/documentation/client_docs/_node.md)
- …

chore(schemas): update get notification by id model and tests

---

Dockerfile
spec/integration/test.js

[Trello card](https://trello.com/c/D1m5uleD/952-run-api-client-integration-tests-as-part-of-new-pipeline)
Some small updates to make the integration tests runnable in the dev environments via the new deploy pipeline.
[Tested in dev-a](https://concourse.notify.tools/teams/dev-a/pipelines/deploy-notify/jobs/test/builds/162) (5 times in a row to check for flakiness)

Make the integration tests compatible with the dev environments
