- README.md
Update README to reflect new module api
> Update README to reflect new module api

- spec/integration/schemas/v0/GET_notifications_return.json
This updates the links object to be consistent with the schema specified in notifications-api.
> Update schema to match notifications-api

- README.md
Quick and basic, should improve this later
> Add get methods to Node doc

- client/api_client.js
- package.json
- spec/api_client.js
- spec/notification.js
Implements https://github.com/alphagov/notifications-python-client/pull/36
> Make secret include API key and service ID 

- client/api_client.js
- package.json
- spec/api_client.js
User agent string added as per other clients
> Added user agent to NODE client requests.

- client/api_client.js
- spec/integration/test.js
sometimes preview was taking more than two seconds to run things
> allow integration tests to take up to 10 seconds

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- DOCUMENTATION.md
- README.md
- client/notification.js
- package.json
- spec/integration/test.js
- spec/notification.js
> Add document upload functionality

- DOCUMENTATION.md
- README.md
> Unfold details for new features in documentation with summary and details tags

- DOCUMENTATION.md
Create Node.js tech docs.
- `README.md`
> Create Node.js tech docs

- CHANGELOG.md
- package.json
A new version will allow us to update this page with the new README: https://www.npmjs.com/package/notifications-node-client
> Release version 4.5.2

- DOCUMENTATION.md
Reverts alphagov/notifications-node-client#73
> Revert "Remove backticks for 'Get the status of multiple messages' statuses"

- DOCUMENTATION.md
Add content so headings do not skip levels. This is to comply with accessibility requirements.
> Add content so headings do not skip levels.

- DOCUMENTATION.md
As per https://github.com/alphagov/notifications-java-client/pull/134 which implements https://github.com/alphagov/notifications-api/pull/2344
> Document `html` property of preview method

- docker/Dockerfile
- docker/Makefile
- package.json
See individual commit messages
> Edit docker file for builds to be run on concourse

- DOCUMENTATION.md
> improve docs - fix anchor links and change how we get notification ids

- DOCUMENTATION.md
actually after seeing the doc changes in the wild they looked a bit verbose. karl's doing a full audit of the docs but we can fix these for now
> remove redundant info in docs

- DOCUMENTATION.md
Corrects inconsistencies in the language and formatting of the reply-to email address section.
> Update reply-to email addresses section

- DOCUMENTATION.md
> Fix header

- CHANGELOG.md
- DOCUMENTATION.md
- client/notification.js
- package.json
- spec/notification.js
> file not doc

- CONTRIBUTING.md
- Makefile
command taken from https://stackoverflow.com/a/33628871.
also remove the release details from CONTRIBUTING.md, pending new concourse pipeline
> add get-client-version command

- CHANGELOG.md
- package.json
this is required by our release pipeline to publish to npm from concourse. set it to the tech docs for the node client
> Add homepage to package.json

- DOCUMENTATION.md
So our docs match our recent change to the API
alphagov/notifications-api#2701
> Update error messages

- DOCUMENTATION.md
- script/test_send.js
- spec/integration/test.js
This work is for this PR to work properly when deploying (otherwise client integrations tests will start failing): https://github.com/alphagov/notifications-api/pull/2751
> Update tests to pass postcode validation and update documentation

- DOCUMENTATION.md
> Fix bracket ordering typo

- CHANGELOG.md
- client/notification.js
- package.json
Fixes issue https://github.com/alphagov/notifications-node-client/issues/136
> Fix incorrect parameter description for `setProxy`

- CHANGELOG.md
- client/notification.js
- package.json
- spec/integration/schemas/v2/definitions.json
- spec/integration/test.js
- spec/notification.js
This updates the client to allow an unsubscribe link to be passed to the `sendEmail` function.
⚠️ Still to do before merging ⚠️
- [notifications-tech-docs repository](https://github.com/alphagov/notifications-tech-docs/blob/main/source/documentation/client_docs/_node.md)
> Unsubscribe link

- CHANGELOG.md
- client/api_client.js
- package-lock.json
- package.json
- spec/api_client.js
Notify team opening our own version of https://github.com/alphagov/notifications-node-client/pull/200 so that concourse can run unit tests against it
- [notifications-tech-docs repository](https://github.com/alphagov/notifications-tech-docs/blob/main/source/documentation/client_docs/_node.md)
> add ability to provide custom Axios instance

- CHANGELOG.md
- client/notification.js
- package.json
Fix a bug in https://github.com/alphagov/notifications-node-client/pull/200 where an internal function isn't exposed.
- [notifications-tech-docs repository](https://github.com/alphagov/notifications-tech-docs/blob/main/source/documentation/client_docs/_node.md)
> expose internal SDK function
